@startuml
title IMKSUSHA I LOVE TMP Diagram

skinparam {
    shadowing false
    backgroundColor #EEEBDC
    borderColor #333333
    arrowColor #333333
}

actor User

rectangle "IMKSUSHA I LOVE TMP Application" {
    User -> (Start)
    User --> (Display "IMKSUSHA I LOVE TMP")
}

@enduml
